import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const pages=['index.html','services/index.html','bridal/index.html','gallery/index.html','locations/index.html'];
let links=0;const external=new Set();
for(const file of pages){const html=fs.readFileSync(file,'utf8');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size,file+' duplicate IDs');for(const match of html.matchAll(/(?:href|src)="([^"]+)"/g)){const url=match[1].replaceAll('&amp;','&');if(url.startsWith('https:')){external.add(url);continue}if(url.startsWith('tel:'))continue;const [relative,hash]=url.split('#');const target=path.resolve(path.dirname(file),relative||path.basename(file));assert(fs.existsSync(target),file+' missing '+target);if(hash){const text=fs.readFileSync(target,'utf8');assert(text.includes(`id="${hash}"`),file+' missing fragment '+url)}links++}assert.match(html,/height="639" alt="Ivan Beauty Salon"/);assert(!html.includes('raw.githubusercontent.com'));}
function luminance(hex){const c=hex.slice(1).match(/../g).map(h=>parseInt(h,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722}
function contrast(a,b){const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)}
const pairs=[];
for(const [mode,paper,surface,ink,muted,gold,focus] of [['light','#f6f2ea','#ece6dc','#24221f','#686158','#795a1e','#946818'],['dark','#22231f','#2d2e28','#f6f2ea','#c5beb2','#dfbd70','#ebc979']]){for(const [surfaceName,bg] of [['paper',paper],['surface',surface]])for(const [name,fg,minimum] of [['text',ink,4.5],['muted',muted,4.5],['gold',gold,4.5],['focus',focus,3]])pairs.push({name:`${mode} ${name}/${surfaceName}`,ratio:contrast(fg,bg),minimum});}
for(const [name,fg,bg,min] of [['gold button','#211e18','#dfbd70',4.5],['gold hover','#211e18','#edd398',4.5],['black button','#f6f2ea','#171816',4.5],['black hover','#f6f2ea','#33352e',4.5],['footer','#c3bfb4','#171816',4.5],['navigation active','#dfbd70','#171816',4.5],['inverse focus','#ebc979','#171816',3],['control border','#797b6e','#171816',3],['lightbox hover','#f6f2ea','#383b31',4.5],['demo label','#d7d1c4','#292a25',4.5]])pairs.push({name,ratio:contrast(fg,bg),minimum:min});
for(const p of pairs)assert(p.ratio>=p.minimum,`${p.name}: ${p.ratio}`);
const assets=fs.readdirSync('assets').map(file=>({file,bytes:fs.statSync('assets/'+file).size,sha256:createHash('sha256').update(fs.readFileSync('assets/'+file)).digest('hex')}));
const gallery=fs.readFileSync('gallery/index.html','utf8');assert.match(gallery,/<img[^>]*photo-5.webp[^>]*fetchpriority="high"/);
const result={status:'pass',scope:'Source checks only; not a fresh live-browser audit',localReferencesAndFragments:links,externalLinks:[...external],contrast:pairs.map(p=>({...p,ratio:Number(p.ratio.toFixed(2))})),assets,totalAssetBytes:assets.reduce((n,a)=>n+a.bytes,0)};
fs.mkdirSync('qa',{recursive:true});fs.writeFileSync('qa/source-audit.json',JSON.stringify(result,null,2));console.log(JSON.stringify({status:result.status,localReferences:links,contrastPairs:pairs.length,totalAssetBytes:result.totalAssetBytes}));
