import {createRequire} from 'node:module';import {readFile,writeFile,mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);const {chromium}=require('playwright');
let axe;try{axe=await readFile(require.resolve('axe-core/axe.min.js'),'utf8')}catch{axe=await readFile('qa/axe.min.js','utf8')}
await mkdir('qa',{recursive:true});
const browser=await chromium.launch({channel:process.platform==='win32'?'msedge':undefined,headless:true});
const errors=[],violations=[],checks=[];const pages=['','services/','bridal/','gallery/','locations/'];
const page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));
async function audit(label){await page.evaluate(axe);const result=await page.evaluate(async()=>await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));if(result.violations.length)violations.push({label,items:result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))});}
async function checkTargets(){const targets=await page.locator('.nav a,.button,.theme,.menu-toggle,.text-link,.footer-links a,.phone,.mobile-bar a,.lightbox button').evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>({label:e.textContent.trim(),width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})));for(const t of targets)assert(t.width>=44&&t.height>=44,`Small target: ${JSON.stringify(t)}`)}
try{
for(const theme of ['light','dark'])for(const url of pages)for(const width of [320,375,430,768,1024,1440]){
 await page.setViewportSize({width,height:900});await page.goto('http://127.0.0.1:4173/demo/'+url);await page.evaluate(t=>{localStorage.setItem('ivan-theme',t)},theme);await page.reload();await page.locator('main img').evaluateAll(async imgs=>{await Promise.all(imgs.filter(i=>i.complete).map(i=>i.decode().catch(()=>{})))});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!overflow,`${url} ${width} ${theme} overflow`);assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('html').getAttribute('data-theme'),theme);await audit(`${url||'home'} ${width} ${theme}`);checks.push(`${url||'home'} ${width} ${theme}`);
 await checkTargets();
 if([375,1440].includes(width)){for(const im of await page.locator('img[src]').all()){if(await im.isVisible()){await im.scrollIntoViewIfNeeded();await im.evaluate(i=>i.decode())}}await page.evaluate(()=>scrollTo(0,0));} if([375,1440].includes(width))await page.screenshot({path:`qa/${url.replace('/','')||'home'}-${width}-${theme}.png`,fullPage:true});
}
console.log('Completed 60 layout/accessibility cases.');
await checkTargets();
await page.setViewportSize({width:375,height:812});await page.goto('http://127.0.0.1:4173/demo/gallery/');
await page.locator('[data-menu]').click();assert.equal(await page.locator('[data-menu]').getAttribute('aria-expanded'),'true');await audit('mobile menu open');await page.keyboard.press('Escape');assert(await page.locator('[data-menu]').evaluate(e=>e===document.activeElement));assert.equal(await page.locator('[data-menu]').getAttribute('aria-expanded'),'false');
await page.locator('[data-photo]').first().click();assert(await page.locator('dialog').evaluate(d=>d.open));assert.equal(await page.locator('#photo-count').innerText(),'Photo 1 of 5');await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#photo-count').innerText(),'Photo 2 of 5');await page.keyboard.press('ArrowLeft');assert.equal(await page.locator('#photo-count').innerText(),'Photo 1 of 5');await page.keyboard.press('ArrowLeft');assert.equal(await page.locator('#photo-count').innerText(),'Photo 5 of 5');await page.locator('#close-photo').focus();await page.keyboard.press('Shift+Tab');assert(await page.locator('#next-photo').evaluate(e=>e===document.activeElement));await page.keyboard.press('Tab');assert(await page.locator('#close-photo').evaluate(e=>e===document.activeElement));await audit('lightbox dark');await page.screenshot({path:'qa/lightbox-mobile.png'});await page.keyboard.press('Escape');assert(await page.locator('[data-photo]').first().evaluate(e=>e===document.activeElement));assert(!(await page.locator('body').getAttribute('class')||'').includes('modal-open'));
await page.locator('button[data-theme]').click();const selected=await page.locator('html').getAttribute('data-theme');await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),selected);
await page.locator('[data-photo]').first().click();await audit('lightbox light');await page.keyboard.press('Escape');
await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');
await page.setViewportSize({width:640,height:800});for(const url of pages){await page.goto('http://127.0.0.1:4173/demo/'+url);await page.addStyleTag({content:'html{font-size:200%}'});assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)),url+' text reflow')}
const denied=await browser.newContext();await denied.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new Error('Storage blocked')}}));const p=await denied.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4173/demo/');await p.locator('button[data-theme]').click();assert.equal(await p.locator('html').getAttribute('data-theme'),'dark');await denied.close();
const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:375,height:812}});const q=await nojs.newPage();for(const url of pages){await q.goto('http://127.0.0.1:4173/demo/'+url);assert(await q.locator('#navigation a').first().isVisible());assert.equal(await q.locator('h1').count(),1)}await nojs.close();
assert.equal(errors.length,0,'JavaScript errors');assert.equal(violations.length,0,JSON.stringify(violations));
await writeFile('qa/results.json',JSON.stringify({date:'2026-10-04',layoutCases:checks.length,axeAudits:63,violations,errors,interactions:['mobile navigation Escape/focus','lightbox arrows/wrap/Tab/Escape/focus/scroll unlock','theme persistence','storage denied','reduced motion','200% text reflow all pages','no-JS navigation all pages','nested base path /demo/'],status:'pass'},null,2));console.log('All checks passed.');
}catch(e){await writeFile('qa/failures.json',JSON.stringify({error:e.message,violations,errors},null,2));throw e}finally{await browser.close()}
